name: K A N T E L I N E N
favicon: null
layout_spectrum: 0.5388734517619014
typography_spectrum: 0.9889232376590371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.2469745920971036
  rhythmicContrast: 0.25
purpose: []
